<?php

/*
 
TIPOS DE DATOS:

ENTEROS (INT/INTEGER) -> 9 
FLOAT/DOUBLE -> 3,18 
STRING (TEXTO) -> 'HOLA SOY STRING'
BOOLEAN (TRUE/FALSE) OR  (1/0)
NULL
ARRAY (COLECCION DE DATOS) [F,4,4,K]
OBJETOS -> {CLAVE:KEY}

 

*/

//NO SE DEFINE EL TIPO DE DATO COMO EN JAVASCRIPT O PYTHON 
//LAS VARIABLES NO PUEDEN EMPEZAR POR UN NUMERO, GUION, SIGNOS MATEMATICOS TAMPOCO Ñ

$NUMERO=100;
$DECIMAL = 27.9;
$TEXTO = 'SOY UN TEXTO';
$VERDADERO = TRUE;
ECHO GETTYPE($NUMERO);
ECHO '<BR>';
ECHO GETTYPE($DECIMAL);
ECHO '<BR>';
ECHO GETTYPE($TEXTO);
ECHO '<BR>';
ECHO GETTYPE($VERDADERO);
ECHO '<BR>';
ECHO $VERDADERO;
ECHO '<BR>';

//DEBUGEAR
$mi_nombre = 'alejo bovet';
var_dump($mi_nombre);







?>
